# Generated by Django 5.1.3 on 2024-12-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_permanent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
