# Generated by Django 5.1.3 on 2024-12-03 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_full_name', models.CharField(max_length=50)),
                ('shipping_address1', models.CharField(max_length=100)),
                ('shipping_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_city', models.CharField(max_length=20)),
                ('shipping_state', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_zipcode', models.CharField(max_length=20)),
                ('shipping_country', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
