# Generated by Django 5.1.3 on 2024-12-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=9999999999, max_length=13),
        ),
    ]
