# Generated by Django 5.1.3 on 2024-12-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_date_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
